### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/touchpad#1]
Hi,

thanks for this tool, surely will come in handy.

I installed it following the instructions in the README, and although it is working fine when I use `tt` there were some errors during the installation:
```
sudo -H pip3 install --upgrade touchpad
[sudo] password for manuel: 
Collecting touchpad
  Downloading touchpad-0.1.3.tar.gz
Collecting pycook (from touchpad)
  Downloading pycook-0.1.20.tar.gz
Building wheels for collected packages: touchpad, pycook
  Running setup.py bdist_wheel for touchpad ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lhpyeve7/touchpad/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpuybcxc0cpip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for touchpad
  Running setup.py clean for touchpad
  Running setup.py bdist_wheel for pycook ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lhpyeve7/pycook/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpwe_bn9_ppip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pycook
  Running setup.py clean for pycook
Failed to build touchpad pycook
Installing collected packages: pycook, touchpad
  Running setup.py install for pycook ... done
  Running setup.py install for touchpad ... done
Successfully installed pycook-0.1.20 touchpad-0.1.3
```
Probably nothing major, since `touchpad` is enabling/disabling the touchpad correctly. Just wanted to let you know.

**Comment by abo-abo** [comment]
Works fine for me on my systems.

Also works fine with this Dockerfile:

    FROM ubuntu:xenial
    RUN apt update && apt install -y software-properties-common
    RUN apt update && apt install -y python3-pip
    RUN pip3 install --upgrade touchpad

Output of `docker build -t temp .`:

    Step 4/4 : RUN pip3 install --upgrade touchpad
     ---> Running in 890fd6441178
    Collecting touchpad
      Downloading touchpad-0.1.3.tar.gz
    Collecting pycook (from touchpad)
      Downloading pycook-0.1.20.tar.gz
    Building wheels for collected packages: touchpad, pycook
      Running setup.py bdist_wheel for touchpad: started
      Running setup.py bdist_wheel for touchpad: finished with status 'done'
      Stored in directory: /root/.cache/pip/wheels/59/ce/72/c2550e02d7acbad4098a132d3089956a4bd22785aafdf99694
      Running setup.py bdist_wheel for pycook: started
      Running setup.py bdist_wheel for pycook: finished with status 'done'
      Stored in directory: /root/.cache/pip/wheels/79/60/f1/1983baeb6545d3e2a70cbad664cfcd247b0cfee324c114aed6
    Successfully built touchpad pycook
    Installing collected packages: pycook, touchpad
    Successfully installed pycook-0.1.20 touchpad-0.1.3
    You are using pip version 8.1.1, however version 9.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
     ---> e5586b05deed
    Removing intermediate container 890fd6441178
    Successfully built e5586b05deed
    Successfully tagged temp:latest

**Comment by manuel-uberti** [comment]
I have a Dell XPS 13 9360, running Ubuntu 16.04.

Since it is working anyway, I guess we can close it here.
